version: "3.8"

x-airflow-common: &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__FERNET_KEY: "0123456789abcdef0123456789abcdef"

    # Warehouse connection vars used by ingestion code + psql inside container
    WAREHOUSE_HOST: warehouse
    WAREHOUSE_PORT: "5432"
    WAREHOUSE_DB: analytics
    WAREHOUSE_USER: dbuser
    WAREHOUSE_PASSWORD: depass

    # dbt settings used by BashOperator
    DBT_PROFILES_DIR: /opt/airflow/dbt
    DBT_PROJECT_DIR: /opt/airflow/dbt/weather_dbt

    # For psql auth
    PGPASSWORD: depass

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./dbt:/opt/airflow/dbt
  user: "50000:0"
  depends_on:
    - airflow_db
    - warehouse

services:
  airflow_db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  warehouse:
    image: postgres:16
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: depass
      POSTGRES_DB: analytics
    ports:
      - "5454:5432"   # host:container
    volumes:
      - warehouse_data:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "
      pip install -r /opt/airflow/dbt/requirements.txt &&
      airflow db migrate &&
      airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

volumes:
  airflow_db_data:
  warehouse_data: